"""Update homework status type

Revision ID: 17585a2d73ff
Revises: e0c72b740ca9
Create Date: 2023-01-02 00:56:44.382237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17585a2d73ff"
down_revision = "e0c72b740ca9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("homeworks", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.INTEGER(),
            type_=sa.String(length=100),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("homeworks", schema=None) as batch_op:
        batch_op.alter_column(
            "status",
            existing_type=sa.String(length=100),
            type_=sa.INTEGER(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###
