# Generated by Django 3.2 on 2023-01-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="name")),
                ("value", models.TextField(verbose_name="value")),
                ("desc", models.TextField(blank=True, verbose_name="description")),
                ("type", models.CharField(max_length=30, verbose_name="type")),
            ],
        ),
    ]
